services:
    db:
        image: postgis/postgis
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - '54321:5432'
        volumes:
            - postgres-data:/var/lib/postgresql:rw

volumes:
    postgres-data:
